export default [
    {symbol:"🐒", id:"monkey"},
    {symbol:"🦍", id:"gorilla"},
    {symbol:"🐕", id:"dog"},
    {symbol:"🐈", id:"cat"},
    {symbol:"🏳️‍🌈", id:"pride"},
    {symbol:"🎲", id:"dice"},
    {symbol:"🎯", id:"target"},
    {symbol:"🐯", id:"tiger_face"},
    {symbol:"🦄", id:"unicorn"},
    {symbol:"🐷", id:"pig"},
    {symbol:"🐘", id:"elephant"},
    {symbol:"🍸", id:"drink"},
    {symbol:"🍆", id:"2"},
    {symbol:"🥑", id:"avocado"},
    {symbol:"🍩", id:"4"},
    {symbol:"💋", id:"kiss"},
];